# Generated by Django 5.1.15 on 2026-08-04 19:42

import django.db.models.deletion
import django.utils.timezone
import identity.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('hi', 'हिन्दी'), ('en', 'English')], default='hi', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_user',
            },
            managers=[
                ('objects', identity.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'role',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('PHONE_CHANGE', 'Phone change')], default='LOGIN', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.SmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_request',
                'indexes': [models.Index(fields=['phone', '-created_at'], name='ix_otp_phone_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='ck_otp_request_attempts')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_granted', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_roles', to='identity.role')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='identity.UserRole', to='identity.role'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['app_user'], name='ix_user_role_app_user'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('app_user', 'role'), name='uq_user_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='ix_app_user_is_active'),
        ),
    ]
