# Generated by Django 5.1.15 on 2026-08-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('identity', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='logins', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('customer__isnull', False)), fields=['customer'], name='ix_app_user_customer'),
        ),
    ]
