# Generated by Django 5.2.17 on 2026-09-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_normalise_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='identity.UserRole', through_fields=('app_user', 'role'), to='identity.role'),
        ),
    ]
