# Generated by Django 5.1.15 on 2026-08-05 19:17

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_auditlog_action_businessprofile'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('latitude', core.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', core.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('photo_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediafile')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='delivery', to='orders.salesorder')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'db_table': 'delivery',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['assigned_user', 'status'], name='ix_delivery_user_status'), models.Index(fields=['-delivered_at'], name='ix_delivery_delivered_at'), models.Index(fields=['status'], name='ix_delivery_status'), models.Index(fields=['updated_at'], name='ix_delivery_updated_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'FAILED'), _negated=True), models.Q(('failure_reason', ''), _negated=True), _connector='OR'), name='ck_delivery_failed_reason'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'DELIVERED'), _negated=True), ('delivered_at__isnull', False), _connector='OR'), name='ck_delivery_delivered_at'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='ck_delivery_coords_paired')],
            },
        ),
    ]
