# Generated by Django 5.1.15 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='outcome_client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
