# Generated by Django 5.1.15 on 2026-08-05 17:26

import core.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=32, unique=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=20)),
                ('source', models.CharField(choices=[('WEB', 'Web admin'), ('PORTAL', 'Retailer portal'), ('APP', 'Field app')], max_length=20)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('subtotal_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_warning_shown', models.BooleanField(default=False)),
                ('credit_override_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('credit_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_overrides', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='customers.customer')),
            ],
            options={
                'db_table': 'sales_order',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('product_code', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=200)),
                ('unit_name', models.CharField(max_length=20)),
                ('unit_price', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('tax_rate_percent', core.fields.PercentField(decimal_places=2, max_digits=5)),
                ('pack_size_snapshot', models.IntegerField()),
                ('quantity', core.fields.QuantityField(decimal_places=3, max_digits=14)),
                ('pack_quantity', core.fields.QuantityField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('discount_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('tax_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('line_total', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('discount_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_lines', to='catalogue.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.salesorder')),
            ],
            options={
                'db_table': 'sales_order_line',
                'ordering': ['sales_order', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='ix_order_customer'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='ix_order_status'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['assigned_user', 'status'], name='ix_order_assigned_status'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['-order_date'], name='ix_order_date'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['updated_at'], name='ix_order_updated_at'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0), ('subtotal_amount__gte', 0), ('tax_amount__gte', 0), ('total_amount__gte', 0)), name='ck_order_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancelled_reason', ''), _negated=True), _connector='OR'), name='ck_order_cancel_reason'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit_override_at__isnull', True), ('credit_override_by__isnull', True)), models.Q(('credit_override_at__isnull', False), ('credit_override_by__isnull', False)), _connector='OR'), name='ck_order_override_pair'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['sales_order'], name='ix_order_line_order'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['product'], name='ix_order_line_product'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('sales_order', 'line_number'), name='uq_sales_order_line'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_order_line_qty'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0), ('tax_amount__gte', 0), ('taxable_amount__gte', 0), ('unit_price__gte', 0)), name='ck_order_line_amounts'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('pack_size_snapshot__gte', 1)), name='ck_order_line_pack_size'),
        ),
    ]
