# Generated by Django 5.1.15 on 2026-08-05 19:17

import core.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0004_alter_auditlog_action_businessprofile'),
        ('customers', '0002_customer_state_code'),
        ('inventory', '0005_stock_movement_append_only'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_key', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note')], max_length=20)),
                ('financial_year', models.CharField(max_length=9)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('current_value', models.BigIntegerField(default=0)),
                ('padding', models.SmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'number series',
                'db_table': 'number_series',
                'ordering': ['series_key', 'financial_year'],
                'constraints': [models.UniqueConstraint(fields=('series_key', 'financial_year'), name='uq_number_series'), models.CheckConstraint(condition=models.Q(('current_value__gte', 0)), name='ck_number_series_value'), models.CheckConstraint(condition=models.Q(('padding__gte', 1), ('padding__lte', 12)), name='ck_number_series_padding')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('seller_legal_name', models.CharField(max_length=200)),
                ('seller_gstin', models.CharField(blank=True, max_length=15)),
                ('seller_address', models.TextField(blank=True)),
                ('seller_state_code', models.CharField(blank=True, max_length=2)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_gstin', models.CharField(blank=True, max_length=15)),
                ('buyer_address', models.TextField(blank=True)),
                ('buyer_state_code', models.CharField(blank=True, max_length=2)),
                ('buyer_state_assumed', models.BooleanField(default=False)),
                ('subtotal_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('discount_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('cgst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sgst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('igst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('round_off_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='customers.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pdf_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediafile')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='orders.salesorder')),
                ('number_series', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='billing.numberseries')),
            ],
            options={
                'db_table': 'invoice',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('seller_legal_name', models.CharField(max_length=200)),
                ('seller_gstin', models.CharField(blank=True, max_length=15)),
                ('seller_address', models.TextField(blank=True)),
                ('seller_state_code', models.CharField(blank=True, max_length=2)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_gstin', models.CharField(blank=True, max_length=15)),
                ('buyer_address', models.TextField(blank=True)),
                ('buyer_state_code', models.CharField(blank=True, max_length=2)),
                ('buyer_state_assumed', models.BooleanField(default=False)),
                ('subtotal_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('discount_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('cgst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sgst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('igst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('round_off_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('credit_note_number', models.CharField(max_length=40, unique=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('credit_note_date', models.DateField()),
                ('reason', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='customers.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reason_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='inventory.reasoncode')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_notes', to='billing.invoice')),
                ('number_series', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='billing.numberseries')),
            ],
            options={
                'db_table': 'credit_note',
                'ordering': ['-credit_note_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('product_code', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=8)),
                ('quantity', core.fields.QuantityField(decimal_places=3, max_digits=14)),
                ('unit_name', models.CharField(max_length=20)),
                ('unit_price', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('discount_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('tax_rate_percent', core.fields.PercentField(decimal_places=2, max_digits=5)),
                ('cgst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sgst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('igst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='billing.creditnote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.product')),
            ],
            options={
                'db_table': 'credit_note_line',
                'ordering': ['credit_note', 'line_number'],
                'indexes': [models.Index(fields=['credit_note'], name='ix_credit_note_line_cn'), models.Index(fields=['product'], name='ix_credit_note_line_product')],
                'constraints': [models.UniqueConstraint(fields=('credit_note', 'line_number'), name='uq_credit_note_line'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_credit_note_line_qty'), models.CheckConstraint(condition=models.Q(('igst_amount', 0), models.Q(('cgst_amount', 0), ('sgst_amount', 0)), _connector='OR'), name='ck_credit_note_line_gst_split')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('product_code', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=8)),
                ('quantity', core.fields.QuantityField(decimal_places=3, max_digits=14)),
                ('unit_name', models.CharField(max_length=20)),
                ('unit_price', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('discount_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('tax_rate_percent', core.fields.PercentField(decimal_places=2, max_digits=5)),
                ('cgst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sgst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('igst_amount', core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='billing.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.product')),
            ],
            options={
                'db_table': 'invoice_line',
                'ordering': ['invoice', 'line_number'],
                'indexes': [models.Index(fields=['invoice'], name='ix_invoice_line_invoice'), models.Index(fields=['product'], name='ix_invoice_line_product')],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'line_number'), name='uq_invoice_line'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_invoice_line_qty'), models.CheckConstraint(condition=models.Q(('igst_amount', 0), models.Q(('cgst_amount', 0), ('sgst_amount', 0)), _connector='OR'), name='ck_invoice_line_gst_split')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-invoice_date'], name='ix_invoice_customer_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='ix_invoice_invoice_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['financial_year'], name='ix_invoice_financial_year'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='ix_invoice_status'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('sales_order__isnull', False)), fields=('sales_order',), name='uq_invoice_sales_order'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('cgst_amount__gte', 0), ('discount_amount__gte', 0), ('igst_amount__gte', 0), ('sgst_amount__gte', 0), ('subtotal_amount__gte', 0), ('taxable_amount__gte', 0), ('total_amount__gte', 0)), name='ck_invoice_amounts'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('igst_amount', 0), models.Q(('cgst_amount', 0), ('sgst_amount', 0)), _connector='OR'), name='ck_invoice_gst_split'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancelled_reason', ''), _negated=True), _connector='OR'), name='ck_invoice_cancel'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['invoice'], name='ix_credit_note_invoice'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['customer', '-credit_note_date'], name='ix_credit_note_cust_date'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['financial_year'], name='ix_credit_note_fy'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('cgst_amount__gte', 0), ('discount_amount__gte', 0), ('igst_amount__gte', 0), ('sgst_amount__gte', 0), ('subtotal_amount__gte', 0), ('taxable_amount__gte', 0), ('total_amount__gt', 0)), name='ck_credit_note_amounts'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('igst_amount', 0), models.Q(('cgst_amount', 0), ('sgst_amount', 0)), _connector='OR'), name='ck_credit_note_gst_split'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='ck_credit_note_reason'),
        ),
    ]
