# Generated by Django 5.1.15 on 2026-08-06 18:49

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_state_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=32, unique=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank transfer'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField()),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_reason', models.TextField(blank=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='customers.customer')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['customer', '-payment_date'], name='ix_payment_customer_date'), models.Index(fields=['method', '-payment_date'], name='ix_payment_method_date'), models.Index(fields=['received_by'], name='ix_payment_received_by')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_amount'), models.CheckConstraint(condition=models.Q(models.Q(('is_reversed', True), _negated=True), models.Q(('reversed_reason', ''), _negated=True), _connector='OR'), name='ck_payment_reversed'), models.CheckConstraint(condition=models.Q(models.Q(('is_reversed', False), ('reversed_at__isnull', True)), models.Q(('is_reversed', True), ('reversed_at__isnull', False)), _connector='OR'), name='ck_payment_reversed_pair')],
            },
        ),
    ]
