# Generated by Django 5.1.15 on 2026-08-17 10:43

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_auditlog_action'),
        ('customers', '0002_customer_state_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('visited_at', models.DateTimeField()),
                ('latitude', core.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', core.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_metres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, choices=[('ORDER_TAKEN', 'Order taken'), ('NO_ORDER', 'No order'), ('SHOP_CLOSED', 'Shop closed')], default='', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visits', to='customers.customer')),
                ('photo_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediafile')),
            ],
            options={
                'db_table': 'visit',
                'indexes': [models.Index(fields=['app_user', '-visited_at'], name='ix_visit_user_date'), models.Index(fields=['customer', '-visited_at'], name='ix_visit_customer_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome', ''), ('outcome__in', ['ORDER_TAKEN', 'NO_ORDER', 'SHOP_CLOSED']), _connector='OR'), name='ck_visit_outcome'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='ck_visit_coords')],
            },
        ),
    ]
