# Generated by Django 5.1.15 on 2026-08-05 06:02

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('road_name', models.CharField(blank=True, max_length=200)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('panchayat', models.CharField(blank=True, max_length=150)),
                ('ward_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zone',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('shop_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('billing_address', models.TextField()),
                ('delivery_address', models.TextField(blank=True)),
                ('credit_limit_amount', core.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('credit_days', models.SmallIntegerField(default=0)),
                ('opening_balance_amount', core.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('latitude', core.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', core.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.zone')),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['shop_name'],
            },
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['assigned_user'], name='ix_zone_assigned_user'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['pin_code'], name='ix_zone_pin_code'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['updated_at'], name='ix_zone_updated_at'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['zone'], name='ix_customer_zone'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='ix_customer_phone'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop_name'], name='ix_customer_shop_name'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['updated_at'], name='ix_customer_updated_at'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='ix_customer_active'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit_amount__gte', 0)), name='ck_customer_credit_limit'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_days__gte', 0)), name='ck_customer_credit_days'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='ck_customer_coords_paired'),
        ),
    ]
