# Generated by Django 5.1.15 on 2026-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
