# Generated by Django 5.1.15 on 2026-08-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('direction', models.CharField(choices=[('IN', 'Increase only'), ('OUT', 'Decrease only'), ('BOTH', 'Either')], default='BOTH', max_length=10)),
                ('is_restockable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reason_code',
                'ordering': ['code'],
            },
        ),
    ]
