# Generated by Django 5.1.15 on 2026-08-05 16:16

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('inventory', '0002_seed_reason_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stock_location',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uq_stock_location_default')],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(default='DEFAULT', max_length=64)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_lots', to='catalogue.product')),
            ],
            options={
                'db_table': 'stock_lot',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', core.fields.QuantityField(decimal_places=3, max_digits=14)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Goods received'), ('ISSUE', 'Goods issued'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return'), ('OPENING', 'Opening stock')], max_length=20)),
                ('source_document_type', models.CharField(blank=True, max_length=30)),
                ('source_document_id', models.BigIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movements', to='inventory.stocklocation')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movements', to='inventory.stocklot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movements', to='catalogue.product')),
                ('reason_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movements', to='inventory.reasoncode')),
            ],
            options={
                'db_table': 'stock_movement',
            },
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['product'], name='ix_stock_lot_product'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(condition=models.Q(('expiry_date__isnull', False)), fields=['expiry_date'], name='ix_stock_lot_expiry'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('product', 'lot_code'), name='uq_stock_lot'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'location', 'lot'], name='ix_stock_mv_prod_loc_lot'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-occurred_at'], name='ix_stock_mv_occurred'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['source_document_type', 'source_document_id'], name='ix_stock_mv_source'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(condition=models.Q(('reason_code__isnull', False)), fields=['reason_code'], name='ix_stock_mv_reason'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('source_document_id__isnull', False), ('reason_code__isnull', False), _connector='OR'), name='ck_stock_movement_has_source'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='ck_stock_movement_qty_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_document_id__isnull', True), ('source_document_type', '')), models.Q(models.Q(('source_document_type', ''), _negated=True), ('source_document_id__isnull', False)), _connector='OR'), name='ck_stock_movement_source_pair'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'RECEIPT'), ('quantity__gt', 0)), models.Q(('movement_type', 'ISSUE'), ('quantity__lt', 0)), ('movement_type__in', ['ADJUSTMENT', 'RETURN', 'OPENING']), _connector='OR'), name='ck_stock_movement_sign_per_type'),
        ),
    ]
