# Generated by Django 5.1.15 on 2026-08-17 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(unique=True)),
                ('device_id', models.CharField(max_length=64)),
                ('operation_type', models.CharField(max_length=40)),
                ('client_created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('DUPLICATE', 'Duplicate'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=20)),
                ('result_entity_type', models.CharField(blank=True, max_length=30)),
                ('result_entity_id', models.BigIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_detail', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_operation',
                'indexes': [models.Index(fields=['device_id', 'client_created_at'], name='ix_sync_op_device_created'), models.Index(condition=models.Q(('status__in', ['DEFERRED', 'REJECTED'])), fields=['status'], name='ix_sync_op_exceptions')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['RECEIVED', 'ACCEPTED', 'DUPLICATE', 'DEFERRED', 'REJECTED'])), name='ck_sync_operation_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('error_code', ''), _negated=True), _connector='OR'), name='ck_sync_operation_rejected')],
            },
        ),
    ]
