"""**K-1 is a procedure risk, and the repository can still hold part of it** (`00` §2.3).

> *The keystore and its passwords are generated once, stored in the password manager, and
> backed up to at least two locations that are not the development machine. This is done at
> M8 and verified at M11. It is never committed to Git (N-11).*

`M8_Design_Review` AR-5 calls losing it *"not an M8 code risk — an M8 **procedure** risk"*,
and that is right: no test can make the operator copy a file to two places. What a test
**can** hold is the part of K-1 that lives in source control, and the M11 inspection found
one real gap and one misplaced rule:

1. **No ignore rule covered the format the procedure produces.** The root `.gitignore` had
   `*.keystore` and `*.jks`; Flutter's generated `mobile/android/.gitignore` has
   `**/*.keystore` and `**/*.jks`. `keytool`'s default store format since JDK 9 is
   **PKCS12**, so the file the documented command writes is a `.p12` — matched by neither,
   and so was `.pepk`. A set that covers every format except the generated one reads as
   protection and is not.
2. **`key.properties` was ignored only by the generated file.** The release build has no
   `signingConfig`; the recipe that supplies one reads `mobile/android/key.properties`,
   holding the store password, key password, alias and path **in clear**. Flutter's
   scaffolding does list it — so this was not an open hole — but that file is regenerated by
   `make mobile-android-scaffold` from the pinned SDK and covers one directory. N-11 is
   repository-wide and is not a rule this repository should be inheriting from a code
   generator.

Both are asserted against the **root `.gitignore`** for that second reason, and never with
`git ls-files` — *"the backend image contains no git"*
(`M10_Security_Review` §NFR-SEC-007), so the right question in the wrong place fails in the
authoritative environment and passes everywhere it does not matter. The mechanism that
prevents the commit is itself a committed file, readable wherever the repository is.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

pytestmark = pytest.mark.adversarial

ROOT = Path(__file__).resolve().parents[3]

GITIGNORE = ROOT / ".gitignore"
GRADLE = ROOT / "mobile" / "android" / "app" / "build.gradle.kts"
RUNBOOK = ROOT / "docs" / "runbooks" / "android-keystore.md"
RUNBOOKS_INDEX = ROOT / "docs" / "runbooks" / "README.md"

#: Read from outside `backend/`; they arrive by bind-mount (`docker/compose.dev.yml`).
REQUIRED_PATHS = (
    ".gitignore",
    "mobile/android/app/build.gradle.kts",
    "docs/runbooks/android-keystore.md",
    "docs/runbooks/README.md",
)

#: Every store format the documented procedure can produce, and the plaintext companion the
#: signing config will read. A pattern set that misses the format actually generated is
#: decoration, which is precisely what was wrong before M11.
KEYSTORE_RULES = ("*.p12", "*.jks", "*.keystore", "*.pepk", "key.properties")

#: Gradle keys that carry a credential. An assignment from a string literal is a secret in
#: source control; an assignment from a properties lookup is the documented shape.
CREDENTIAL_KEYS = ("storePassword", "keyPassword", "keyAlias", "storeFile")


def test_every_path_this_suite_reads_is_visible_from_inside_the_container():
    """Fail on the plumbing *as* plumbing, before any contract is evaluated.

    The M8 mobile suite and the M10 security suite were both written a commit before their
    bind-mounts and both failed on `FileNotFoundError` rather than on their subject. Every
    path above is already mounted by an earlier milestone; this test is what notices if one
    is removed.
    """
    missing = [path for path in REQUIRED_PATHS if not (ROOT / path).exists()]
    assert not missing, (
        f"not visible at {ROOT}: {missing}. These arrive by bind-mount — add them to the "
        "`app` service volumes in `docker/compose.dev.yml`."
    )


def _ignore_rules() -> set[str]:
    """`.gitignore`'s rules, comments and blanks removed.

    The same parse as `test_security_nfrs.test_an_env_file_cannot_be_committed`, for the same
    reason: it is the mechanism, and it is in source control.
    """
    return {
        line.strip()
        for line in GITIGNORE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    }


# ----------------------------------------------------- the mechanism that prevents a commit
def test_no_keystore_format_the_procedure_produces_can_be_committed():
    """**The gap, stated as the thing it allows.**

    Nothing matched the `.p12` that `keytool -genkeypair -storetype PKCS12` writes — not
    `*.jks` here, not `**/*.jks` in Flutter's generated `mobile/android/.gitignore`. A rule
    set that covers every format *except* the one the runbook tells the operator to create
    is worse than none, because it reads as protection.

    **The root file, deliberately.** `key.properties` is also listed in the generated
    Android `.gitignore`, and that is not where an N-11 rule should live: it is scaffolding
    `make mobile-android-scaffold` rewrites from the pinned SDK, and it guards one directory.
    """
    rules = _ignore_rules()
    assert rules, ".gitignore parsed to nothing — every assertion below would be vacuous"

    missing = [rule for rule in KEYSTORE_RULES if rule not in rules]
    assert not missing, (
        f"the root `.gitignore` does not refuse {missing}. K-1: the keystore and the file "
        "holding its passwords are never committed. Flutter's generated "
        "`mobile/android/.gitignore` is not a substitute — `make mobile-android-scaffold` "
        "rewrites it, and it guards one directory while N-11 is repository-wide."
    )


def test_the_ignore_rules_this_suite_names_are_the_ones_the_runbook_tells_the_operator_to_check():
    """Anti-vacuity across the two halves.

    §6 of the runbook has the operator run `git check-ignore` on specific names. If this
    suite and that list drift apart, one of them is enforcing a rule nobody was told about
    or the operator is checking a rule nothing holds — the *"one fact in two places"* defect
    that `docker/compose.dev.yml` records twice.
    """
    runbook = RUNBOOK.read_text(encoding="utf-8")
    for rule in KEYSTORE_RULES:
        # `*.p12` → `p12`; the runbook names a concrete filename, not the glob.
        token = rule.removeprefix("*.")
        assert token in runbook, (
            f"the runbook never mentions `{token}`, yet this suite requires `{rule}` to be "
            "ignored. The operator's check and the gate's check must be the same check."
        )
    assert "check-ignore" in runbook, (
        "the runbook no longer has the operator verify the ignore rules are real rather "
        "than assumed"
    )


# ------------------------------------------------------------------- the signing path
def _release_block() -> str:
    """The `release` build type's body, braces balanced.

    A regex to the next `}` would stop at the first nested block, so the depth is counted.
    """
    source = GRADLE.read_text(encoding="utf-8")
    start = re.search(r"\brelease\s*\{", source)
    assert start, "the `release` build type is gone from `build.gradle.kts`"

    depth = 0
    for index in range(start.end() - 1, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[start.end() : index]
    raise AssertionError("unbalanced braces in the `release` build type")


def test_the_release_build_is_never_signed_with_the_debug_key():
    """**The line Flutter generates, and why it was deleted.**

    `flutter create` writes `signingConfig = signingConfigs.getByName("debug")` into the
    release block so that `flutter run --release` works out of the box. It makes a release
    build that installs, runs, looks finished, and is signed with a key that is in every
    Flutter installation on earth. Play rejects it; worse, a sideloaded APK does not, so the
    first thing a retailer could be handed is an unsigned-in-effect build.

    The comment in that block explains this. A comment is not a gate — this is.
    """
    block = _release_block()
    code = "\n".join(line for line in block.splitlines() if not line.lstrip().startswith("//"))

    assert "debug" not in code, (
        "the release build type references the debug signing identity again. `flutter "
        "create` generates exactly this line; deleting it was deliberate (`00` §2.3)."
    )


def test_no_signing_credential_is_ever_written_into_the_build_file():
    """The durable invariant — it holds **now and after** the keystore exists.

    Today the release block is empty and this is trivially true. The value is later: when
    §8's `signingConfig` is added, it must read from the gitignored `key.properties`, and
    the shortest path to a working release build is to paste the password in here instead.
    That file is committed, so a literal is a secret in source control that no scanner
    entropy heuristic would reliably flag — the `SECRET_KEY` default's argument exactly
    (`test_security_nfrs`).
    """
    source = GRADLE.read_text(encoding="utf-8")
    code = "\n".join(line for line in source.splitlines() if not line.lstrip().startswith("//"))

    for key in CREDENTIAL_KEYS:
        literal = re.search(rf'\b{key}\s*=\s*["\']', code)
        assert not literal, (
            f"`{key}` is assigned a literal in `build.gradle.kts`, which is committed. Read "
            "it from `mobile/android/key.properties` instead — gitignored, per-machine, "
            "never in source control (N-11)."
        )


def test_a_signing_config_may_only_appear_alongside_the_properties_file_that_feeds_it():
    """Conditional, because the config does not exist yet and must not be forced to.

    Writing one now would point at a keystore that has not been generated and turn a clear
    refusal into a confusing one. But *if* it appears, it must be fed from the documented
    source — the one place the passwords are allowed to be.
    """
    source = GRADLE.read_text(encoding="utf-8")
    code = "\n".join(line for line in source.splitlines() if not line.lstrip().startswith("//"))

    if "signingConfig" not in code:
        return  # The documented state: no keystore, therefore no config. Nothing to check.

    assert "key.properties" in code, (
        "a signing configuration exists but reads nothing from `key.properties`. The "
        "credentials are coming from somewhere else — check it is not this file, and not "
        "the environment of a machine that is not the release machine."
    )


# ----------------------------------------------------------------- the procedure itself
def test_the_procedure_is_deterministic_enough_to_execute():
    """K-1 is *"done at M8"* and M8 entry condition 4 was never ticked.

    The reason is that no procedure existed — `rotate-secrets` said so outright: *"there is
    no procedure."* A rule whose execution depends on the operator inventing the parameters
    produces a keystore whose alias and format the next reader has to guess, and guessing is
    not available when the key cannot be regenerated.
    """
    runbook = RUNBOOK.read_text(encoding="utf-8")

    assert "keytool -genkeypair" in runbook, "the runbook does not give the generation command"
    assert "-alias upload" in runbook, (
        "the alias is not fixed. `keytool -list` needs it, the signing config names it, and "
        "it cannot be changed after the first upload to Play"
    )
    assert "keytool -list -v" in runbook, (
        "nothing verifies the backups. `00` §14 B-1: a backup that has never been restored "
        "does not count as a backup — a keystore copy is the same bet with a worse loss"
    )
    assert "SHA-256" in runbook, (
        "no fingerprint is recorded, so there is no non-secret way to prove two copies are "
        "the same key"
    )
    assert re.search(r"two.{0,40}(locations|backups|destinations)", runbook, re.IGNORECASE), (
        "the runbook does not require two off-machine backups, which is the whole of K-1"
    )


def test_the_runbook_is_reachable_from_the_index():
    """A runbook nobody can find is a runbook nobody runs (B-4).

    `00` §4.3: *a restore procedure first written during an outage is not a procedure*. One
    that exists but is unlisted is the same failure with an extra step.
    """
    index = RUNBOOKS_INDEX.read_text(encoding="utf-8")
    assert "android-keystore" in index, "the K-1 runbook is not listed in `docs/runbooks/README.md`"


def test_the_keystore_log_records_no_secret_and_no_invented_row():
    """The posture the restore rehearsal and ACT-E logs already take.

    **Not an assertion that the log is empty** — that was the defect in
    `test_the_rehearsal_log_is_not_filled_with_an_invented_row`, which passed only until a
    real run was recorded and then had to be replaced. This checks *well-formedness*: a
    filled row carries a real SHA-256 fingerprint, and nothing in the table is a credential.
    It holds before the keystore exists and after.
    """
    lines = RUNBOOK.read_text(encoding="utf-8").splitlines()

    headers = [index for index, line in enumerate(lines) if line.startswith("| Date | Alias |")]
    assert len(headers) == 1, (
        "the K-1 log table's header is gone or duplicated, so this contract would check "
        "nothing or check the wrong table"
    )
    header = headers[0]

    rows = []
    for line in lines[header + 2 :]:
        if not line.startswith("|"):
            break
        rows.append([cell.strip() for cell in line.strip("|").split("|")])

    assert rows, "the log has no body row at all, not even the empty placeholder"

    for row in rows:
        assert len(row) == 9, f"log row has {len(row)} cells, not the header's 9: {row}"
        if not any(row):
            continue  # The unfilled placeholder. The keystore does not exist yet.

        fingerprint = row[5]
        assert re.fullmatch(r"(?:[0-9A-F]{2}:){31}[0-9A-F]{2}", fingerprint.upper()), (
            f"`{fingerprint}` is not a SHA-256 fingerprint as `keytool -list -v` prints it. "
            "A row that cannot identify the key proves nothing was verified."
        )
        assert "password" not in " ".join(row).lower(), (
            "a password, or a reference to one, is recorded in a committed file (N-11). The "
            "log carries non-secret facts only: date, alias, format, fingerprint, operator."
        )
