# Generated by Django 5.1.15 on 2026-08-05 06:02

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_auditlog_action_mediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=8)),
                ('tax_rate_percent', core.fields.PercentField(decimal_places=2, default=0, max_digits=5)),
                ('selling_price', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('unit_name', models.CharField(default='PCS', max_length=20)),
                ('pack_size', models.IntegerField(default=1)),
                ('pack_name', models.CharField(blank=True, default='CASE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('image_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.mediafile')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='ix_product_name'), models.Index(fields=['updated_at'], name='ix_product_updated_at'), models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='ix_product_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='ck_product_selling_price'), models.CheckConstraint(condition=models.Q(('tax_rate_percent__gte', 0), ('tax_rate_percent__lte', 100)), name='ck_product_tax_rate'), models.CheckConstraint(condition=models.Q(('pack_size__gte', 1)), name='ck_product_pack_size')],
            },
        ),
    ]
