"""Order payload shapes (05 §9.3). Money is a decimal string (AD-02)."""

from __future__ import annotations

from rest_framework import serializers


class OrderLineSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    line_number = serializers.IntegerField(read_only=True)
    product_id = serializers.IntegerField(read_only=True)
    product_code = serializers.CharField(read_only=True)
    product_name = serializers.CharField(read_only=True)
    quantity = serializers.DecimalField(max_digits=14, decimal_places=3, read_only=True)
    pack_quantity = serializers.DecimalField(
        max_digits=14, decimal_places=3, read_only=True, allow_null=True
    )
    unit_name = serializers.CharField(read_only=True)
    unit_price = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)
    discount_amount = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)
    tax_rate_percent = serializers.DecimalField(max_digits=5, decimal_places=2, read_only=True)
    taxable_amount = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)
    tax_amount = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)
    line_total = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)


class OrderSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    order_number = serializers.CharField(read_only=True)
    client_uuid = serializers.UUIDField(read_only=True, allow_null=True)
    customer_id = serializers.IntegerField(read_only=True)
    customer_code = serializers.CharField(source="customer.code", read_only=True)
    customer_name = serializers.CharField(source="customer.shop_name", read_only=True)
    status = serializers.CharField(read_only=True)
    source = serializers.CharField(read_only=True)
    order_date = serializers.DateField(read_only=True)
    expected_delivery_date = serializers.DateField(read_only=True, allow_null=True)
    subtotal_amount = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)
    discount_amount = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)
    tax_amount = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)
    total_amount = serializers.DecimalField(max_digits=14, decimal_places=2, read_only=True)
    credit_warning_shown = serializers.BooleanField(read_only=True)
    cancelled_reason = serializers.CharField(read_only=True)
    notes = serializers.CharField(read_only=True)
    lines = OrderLineSerializer(many=True, read_only=True)
    created_at = serializers.DateTimeField(read_only=True)


class OrderLineWriteSerializer(serializers.Serializer):
    """Exactly one of ``quantity`` (base units) or ``pack_quantity`` (packs).

    Not a number plus a unit flag: two fields encoding one fact can disagree. Validated
    here so the client gets a field-level error, and again in the service so no caller
    can bypass it (05 §10.2, M3-2).
    """

    product_id = serializers.IntegerField()
    quantity = serializers.DecimalField(
        max_digits=14, decimal_places=3, required=False, allow_null=True, default=None
    )
    pack_quantity = serializers.DecimalField(
        max_digits=14, decimal_places=3, required=False, allow_null=True, default=None
    )
    discount_amount = serializers.DecimalField(
        max_digits=14, decimal_places=2, required=False, default=0
    )

    def validate(self, attrs: dict) -> dict:
        base, packs = attrs.get("quantity"), attrs.get("pack_quantity")
        if (base is None) == (packs is None):
            raise serializers.ValidationError(
                {"quantity": "Give a quantity in base units or in packs, not both."}
            )
        # Hoisted so the narrowing is visible. The guard above proves exactly one of the
        # two was given, so `quantity is None` is unreachable — but that proof lives in a
        # derived boolean and no reader, human or static, can follow it from here.
        quantity = base if base is not None else packs
        if quantity is None or quantity <= 0:
            raise serializers.ValidationError({"quantity": "Quantity must be greater than zero."})
        return attrs


class OrderWriteSerializer(serializers.Serializer):
    # AD-09 / M3-5: generated by the client before the first attempt, reused on retry.
    client_uuid = serializers.UUIDField(required=False, allow_null=True, default=None)
    # Omitted by RETAILER — derived from the token, never accepted (AD-11).
    customer_id = serializers.IntegerField(required=False, allow_null=True, default=None)
    expected_delivery_date = serializers.DateField(required=False, allow_null=True, default=None)
    notes = serializers.CharField(required=False, allow_blank=True, default="")
    override_credit = serializers.BooleanField(required=False, default=False)
    lines = OrderLineWriteSerializer(many=True, allow_empty=False)


class OrderCancelSerializer(serializers.Serializer):
    reason = serializers.CharField(max_length=500)


class CreditStatusSerializer(serializers.Serializer):
    credit_limit_amount = serializers.DecimalField(max_digits=14, decimal_places=2)
    exposure_amount = serializers.DecimalField(max_digits=14, decimal_places=2)
    available_amount = serializers.DecimalField(max_digits=14, decimal_places=2)
    breached = serializers.BooleanField()
    mode = serializers.CharField()
