# Generated by Django 5.1.15 on 2026-08-05 19:17

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_state_code'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note'), ('PAYMENT', 'Payment'), ('OPENING', 'Opening balance'), ('ADJUSTMENT', 'Adjustment'), ('WRITE_OFF', 'Write off')], max_length=20)),
                ('amount', core.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('source_document_type', models.CharField(blank=True, max_length=30)),
                ('source_document_id', models.BigIntegerField(blank=True, null=True)),
                ('narration', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='customers.customer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='orders.salesorder')),
            ],
            options={
                'verbose_name': 'customer ledger entry',
                'verbose_name_plural': 'customer ledger entries',
                'db_table': 'customer_ledger_entry',
                'ordering': ['customer', 'entry_date', 'id'],
                'indexes': [models.Index(fields=['customer', 'entry_date', 'id'], name='ix_cle_customer_date'), models.Index(fields=['source_document_type', 'source_document_id'], name='ix_cle_source'), models.Index(fields=['entry_type', 'entry_date'], name='ix_cle_entry_type_date'), models.Index(condition=models.Q(('sales_order__isnull', False)), fields=['sales_order'], name='ix_cle_sales_order')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ck_cle_amount_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('source_document_id__isnull', True), ('source_document_type', '')), models.Q(models.Q(('source_document_type', ''), _negated=True), ('source_document_id__isnull', False)), _connector='OR'), name='ck_cle_source_pair'), models.CheckConstraint(condition=models.Q(models.Q(('entry_type__in', ['INVOICE', 'OPENING']), ('amount__gt', 0)), models.Q(('entry_type__in', ['PAYMENT', 'CREDIT_NOTE', 'WRITE_OFF']), ('amount__lt', 0)), ('entry_type', 'ADJUSTMENT'), _connector='OR'), name='ck_cle_sign')],
            },
        ),
    ]
