# Generated by Django 5.1.15 on 2026-08-06 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_state_code'),
        ('ledger', '0002_ledger_append_only'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'OPENING')), fields=('customer',), name='uq_cle_one_opening_per_customer'),
        ),
    ]
