# Generated by Django 5.1.15 on 2026-08-04 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_role_code', models.CharField(blank=True, max_length=32)),
                ('surface', models.CharField(choices=[('WEB', 'Web admin'), ('API', 'API'), ('SYSTEM', 'System')], max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('ISSUE', 'Issue'), ('CANCEL', 'Cancel'), ('CREDIT_LIMIT_CHANGE', 'Credit limit change'), ('CREDIT_OVERRIDE', 'Credit override'), ('PRICE_CHANGE', 'Price change'), ('STOCK_ADJUST', 'Stock adjustment'), ('PAYMENT_REVERSE', 'Payment reversal'), ('ROLE_GRANT', 'Role granted'), ('ROLE_REVOKE', 'Role revoked'), ('LOGIN_SUCCESS', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed')], max_length=30)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit entries',
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-occurred_at'], name='ix_audit_entity'), models.Index(fields=['actor_user', '-occurred_at'], name='ix_audit_actor_date'), models.Index(fields=['action', '-occurred_at'], name='ix_audit_action_date')],
            },
        ),
    ]
