# Generated by Django 5.1.15 on 2026-08-05 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audit_log_append_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('ISSUE', 'Issue'), ('CANCEL', 'Cancel'), ('CREDIT_LIMIT_CHANGE', 'Credit limit change'), ('CREDIT_OVERRIDE', 'Credit override'), ('UPDATE', 'Update'), ('DEACTIVATE', 'Deactivate'), ('PRICE_CHANGE', 'Price change'), ('STOCK_ADJUST', 'Stock adjustment'), ('PAYMENT_REVERSE', 'Payment reversal'), ('ROLE_GRANT', 'Role granted'), ('ROLE_REVOKE', 'Role revoked'), ('LOGIN_SUCCESS', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed')], max_length=30),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('purpose', models.CharField(choices=[('PRODUCT_IMAGE', 'Product image'), ('DELIVERY_PHOTO', 'Delivery photo'), ('VISIT_PHOTO', 'Visit photo'), ('INVOICE_PDF', 'Invoice PDF'), ('OFFER_IMAGE', 'Offer image'), ('LOGO', 'Business logo')], max_length=30)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_file',
                'indexes': [models.Index(fields=['purpose', '-uploaded_at'], name='ix_media_purpose_uploaded'), models.Index(fields=['sha256'], name='ix_media_sha256')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='ck_media_size')],
            },
        ),
    ]
