# Generated by Django 5.1.15 on 2026-08-05 17:26

import core.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_action_mediafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('ISSUE', 'Issue'), ('CANCEL', 'Cancel'), ('CREDIT_LIMIT_CHANGE', 'Credit limit change'), ('CREDIT_OVERRIDE', 'Credit override'), ('UPDATE', 'Update'), ('CONFIRM', 'Confirm'), ('DISCOUNT_APPLIED', 'Manual discount applied'), ('DEACTIVATE', 'Deactivate'), ('PRICE_CHANGE', 'Price change'), ('STOCK_ADJUST', 'Stock adjustment'), ('PAYMENT_REVERSE', 'Payment reversal'), ('ROLE_GRANT', 'Role granted'), ('ROLE_REVOKE', 'Role revoked'), ('LOGIN_SUCCESS', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed')], max_length=30),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('invoice_footer', models.TextField(blank=True)),
                ('max_manual_discount_percent', core.fields.PercentField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('credit_limit_mode', models.CharField(choices=[('WARN', 'Warn and allow override'), ('BLOCK', 'Refuse the order')], default='WARN', max_length=10)),
                ('otp_expiry_minutes', models.SmallIntegerField(default=10)),
                ('logo_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediafile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_profile',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ck_business_profile_singleton'), models.CheckConstraint(condition=models.Q(('max_manual_discount_percent__gte', 0), ('max_manual_discount_percent__lte', 100)), name='ck_business_profile_discount'), models.CheckConstraint(condition=models.Q(('otp_expiry_minutes__gt', 0)), name='ck_business_profile_otp')],
            },
        ),
    ]
