# Generated by Django 5.1.15 on 2026-08-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_action_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('ISSUE', 'Issue'), ('CANCEL', 'Cancel'), ('CREDIT_LIMIT_CHANGE', 'Credit limit change'), ('CREDIT_OVERRIDE', 'Credit override'), ('UPDATE', 'Update'), ('CONFIRM', 'Confirm'), ('DISCOUNT_APPLIED', 'Manual discount applied'), ('DEACTIVATE', 'Deactivate'), ('PRICE_CHANGE', 'Price change'), ('STOCK_ADJUST', 'Stock adjustment'), ('PAYMENT_REVERSE', 'Payment reversal'), ('ROLE_GRANT', 'Role granted'), ('ROLE_REVOKE', 'Role revoked'), ('OWNER_BOOTSTRAP', 'Owner bootstrapped'), ('LOGIN_SUCCESS', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed')], max_length=30),
        ),
    ]
